Repository BuildForSDGCohort2/Team-220-EnhancedFarmers-Frontend, pull requests merged in 2020-09, with the labels that each got.

#32 just added a navbar
  .eslintrc.json
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/componentStyles/navbarStyles.css
  src/components/forms/farmRegistrationForm.jsx
  src/components/forms/farmerRegisterForm.jsx
  src/components/navBarCOmponent.jsx
  src/components/reUsableComponents/displaySingleitemComponent.jsx
  src/components/reUsableComponents/itemsDisplayOnPage.jsx
  src/index.js
  src/serviceWorker.js
Labels: chore

#39 Calling back
  .eslintrc.json
  README.md
  package-lock.json
  package.json
  procfile
  server.js
  src/App.js
  src/components/forms/customerRegisterFormComponent.jsx
  src/components/forms/farmerLoginForm.jsx
  src/components/forms/farmerRegisterForm.jsx
  src/components/forms/formStyles/centerContent.css
  src/components/forms/productRegisterForm.jsx
  src/components/forms/profetionalRegComponent.jsx
  src/components/navBarCOmponent.jsx
  src/components/pages/homePageComponent.jsx
  src/components/pages/pageStyles/detail.css
  src/components/pages/productDetailsPage.jsx
  src/components/reUsableComponents/displaySingleitemComponent.jsx
  src/components/reUsableComponents/fileInput.jsx
  src/components/reUsableComponents/formComponent.jsx
  src/components/reUsableComponents/input.jsx
  src/components/reUsableComponents/searchBox.jsx
  src/components/reUsableComponents/select.jsx
  src/components/reUsableComponents/table.jsx
  src/components/reUsableComponents/tableBody.jsx
  src/components/reUsableComponents/tableHeaders.jsx
  src/components/reUsableComponents/tableReUse.jsx
  src/config.json
  src/images/pic.jpg
  src/index.css
  src/services/authServices.js
  src/services/httpServices.js
  src/services/paginate.js
  src/services/professionals.js
  src/services/tabldata.js
Labels: enhancement

#43 just working pushing professional page designs
  src/App.js
  src/components/forms/profetionalRegComponent.jsx
  src/components/pages/pageStyles/detail.css
  src/components/pages/professionalDetails.jsx
  src/components/pages/professionalsDisplayPage.jsx
  src/components/reUsableComponents/formComponent.jsx
  src/components/reUsableComponents/tableBody.jsx
  src/components/reUsableComponents/tableReUse.jsx
  src/services/professionals.js
Labels: enhancement

#44 Homepage
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/pages/Footer.js
  src/components/pages/homePageComponent.jsx
  src/images/SDG.jpg
  src/images/Spinach.jpg
  src/images/andela.png
  src/images/ginger.jpg
  src/images/mixed.jpg
Labels: enhancement

#56 add investors section on our home page
  package-lock.json
  package.json
  src/components/componentStyles/footer.css
  src/components/footerComponent.jsx
  src/components/pages/homePageComponent.jsx
  src/components/pages/pageStyles/homePage.css
  src/images/facebook.png
Labels: enhancement

#57 just added a few farmer links
  src/App.js
  src/components/forms/farmerLoginForm.jsx
  src/components/forms/farmerRegisterForm.jsx
  src/components/forms/farmerRegisterFprm.jsx
  src/components/forms/formStyles/centerContent.css
  src/components/loginComponent.jsx
  src/index.js
  src/services/authServices.js
  src/services/farmers.js
Labels: enhancement

#58 just a connecting farmer backend to front end
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/components/footerComponent.jsx
  src/components/navBarCOmponent.jsx
  src/components/pages/approveFarmer.jsx
  src/components/pages/farmerDetailsPage.jsx
  src/components/pages/farmersPageComponent.jsx
  src/components/pages/homePageComponent.jsx
  src/components/pages/investorsPage.jsx
  src/components/pages/pageStyles/homePage.css
  src/index.js
  src/services/farmers.js
Labels: enhancement

#60 Modifyfootercontent
  src/components/componentStyles/footer.css
  src/components/componentStyles/navbarStyles.css
  src/components/footerComponent.jsx
  src/components/navBarCOmponent.jsx
  src/components/pages/homePageComponent.jsx
  src/components/pages/pageStyles/homePage.css
Labels: enhancement

#61 just connected projects endpoints
  .eslintrc.json
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/robots.txt
  src/App.js
  src/App.test.js
  src/components/forms/projectCreationForm.jsx
  src/components/navBarCOmponent.jsx
  src/components/pages/farmersPageComponent.jsx
  src/components/pages/pageStyles/detail.css
  src/components/pages/pageStyles/homePage.css
  src/components/pages/professionalsDisplayPage.jsx
  src/components/pages/projectsPage.jsx
  src/components/reUsableComponents/formComponent.jsx
  src/logo.svg
  src/services/projects.js
Labels: chore

#65 just connect ui to backend for products
  src/App.js
  src/components/forms/productRegisterForm.jsx
  src/components/forms/profetionalRegComponent.jsx
  src/components/forms/projectCreationForm.jsx
  src/components/logoutComponet.jsx
  src/components/navBarCOmponent.jsx
  src/components/pages/pageStyles/homePage.css
  src/components/pages/productsPageComponent.jsx
  src/components/pages/professionalsDisplayPage.jsx
  src/components/pages/projectsPage.jsx
  src/components/reUsableComponents/displaySingleitemComponent.jsx
  src/components/reUsableComponents/formComponent.jsx
  src/components/reUsableComponents/itemsDisplayOnPage.jsx
  src/services/products.js
Labels: enhancement

#73 just linking backend to front for customers
  src/App.js
  src/components/componentStyles/login.css
  src/components/componentStyles/navbarStyles.css
  src/components/forms/customerLoginComponet.jsx
  src/components/forms/customerRegisterFormComponent.jsx
  src/components/forms/farmerLoginForm.jsx
  src/components/forms/productRegisterForm.jsx
  src/components/forms/profetionalRegComponent.jsx
  src/components/forms/updateCustomerPassword.jsx
  src/components/loginComponent.jsx
  src/components/navBarCOmponent.jsx
  src/components/pages/customerProfile.jsx
  src/components/pages/customersPage.jsx
  src/components/pages/pageStyles/detail.css
  src/components/pages/productsPageComponent.jsx
  src/components/pages/professionalDetails.jsx
  src/components/pages/professionalsDisplayPage.jsx
  src/components/pages/projectsPage.jsx
  src/components/reUsableComponents/displaySingleitemComponent.jsx
  src/components/reUsableComponents/itemsDisplayOnPage.jsx
  src/components/reUsableComponents/reusableStylesComponent/cardStyle.css
  src/index.css
  src/services/authServices.js
  src/services/customers.js
  src/services/demoData.js
  src/services/products.js
  src/services/projects.js
Labels: enhancement

#72 Responsiveness
  src/components/componentStyles/footer.css
  src/components/componentStyles/login.css
  src/components/forms/farmRegistrationForm.jsx
  src/components/forms/farmerRegisterForm.jsx
  src/components/forms/formStyles/centerContent.css
  src/components/forms/projectCreationForm.jsx
  src/components/pages/homePageComponent.jsx
  src/components/pages/pageStyles/homePage.css
  src/components/reUsableComponents/displaySingleitemComponent.jsx
  src/components/reUsableComponents/formComponent.jsx
  src/components/reUsableComponents/reusableStylesComponent/cardStyle.css
  src/components/reUsableComponents/reusableStylesComponent/flexDisplay.css
  src/images/SDG.jpg
  src/images/sdgg.jpg
Labels: chore

#76 Issues
  src/App.js
  src/components/componentStyles/footer.css
  src/components/componentStyles/login.css
  src/components/forms/farmRegistrationForm.jsx
  src/components/forms/farmerRegisterForm.jsx
  src/components/forms/formStyles/centerContent.css
  src/components/navBarCOmponent.jsx
  src/components/pages/pageStyles/detail.css
  src/components/pages/pageStyles/homePage.css
  src/components/pages/professionalDetails.jsx
  src/components/pages/projectsPage.jsx
  src/components/reUsableComponents/displaySingleitemComponent.jsx
  src/components/reUsableComponents/reusableStylesComponent/cardStyle.css
  src/components/reUsableComponents/reusableStylesComponent/flexDisplay.css
  src/components/reUsableComponents/table.jsx
Labels: bug, chore

#79 just did customer details
  src/App.js
  src/components/forms/updateCustomerImage.jsx
  src/components/forms/updateCustomerPassword.jsx
  src/components/navBarCOmponent.jsx
  src/components/pages/customerProfile.jsx
  src/components/pages/customerProfilePage.jsx
  src/components/pages/customersPage.jsx
  src/components/pages/farmersPageComponent.jsx
  src/components/pages/investorsPage.jsx
  src/components/pages/professionalsDisplayPage.jsx
  src/components/pages/projectsPage.jsx
  src/components/reUsableComponents/formComponent.jsx
  src/components/reUsableComponents/itemsDisplayOnPage.jsx
  src/components/reUsableComponents/tableReUse.jsx
  src/services/customers.js
  src/services/orders.js
Labels: bug, chore, enhancement
